[package]
name = "rekordbox-core"
version.workspace = true
edition = "2021"

[dependencies]
binrw.workspace = true
serde.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.13"
